import { deleteService, saveService } from "@/actions/admin";
import { prisma } from "@/lib/prisma";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";

function ServiceForm({ service }: { service?: any }) {
  return <form action={saveService} className="card grid gap-4 p-5"><input type="hidden" name="id" value={service?.id || ""} /><div className="grid gap-4 md:grid-cols-2"><div><label className="label">Title</label><input className="field" name="title" defaultValue={service?.title} required /></div><div><label className="label">Slug</label><input className="field" name="slug" defaultValue={service?.slug} required /></div></div><div><label className="label">Description</label><textarea className="field min-h-28" name="description" defaultValue={service?.description} required /></div><div><label className="label">Technologies (comma separated)</label><input className="field" name="technologies" defaultValue={service?.technologies?.map((t: any) => t.name).join(", ") || ""} /></div><div className="flex flex-wrap items-end gap-5"><div><label className="label">Display order</label><input className="field w-28" name="sortOrder" type="number" min="0" defaultValue={service?.sortOrder ?? 0} /></div><label className="mb-3 flex items-center gap-2 font-semibold"><input type="checkbox" name="published" defaultChecked={service ? service.published : true} /> Published</label><button className="btn btn-primary" type="submit">{service ? "Update Service" : "Create Service"}</button></div></form>;
}

export default async function AdminServicesPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [services, query] = await Promise.all([prisma.service.findMany({ orderBy: [{ sortOrder: "asc" }, { title: "asc" }], include: { technologies: true, _count: { select: { bookings: true } } } }), searchParams]);
  return <><AdminPageHeader title="Services" description="Create, edit, publish/unpublish and order the services shown publicly." />{query.saved && <div className="alert-success mb-5">Service saved.</div>}{query.error && <div className="alert-error mb-5">{query.error}</div>}<ServiceForm /><div className="mt-7 grid gap-5">{services.map((s) => <div key={s.id}><ServiceForm service={s} /><div className="-mt-2 flex items-center justify-end gap-3 px-5 pb-3"><span className="muted text-xs">{s._count.bookings} booking(s)</span><form action={deleteService}><input type="hidden" name="id" value={s.id} /><button className="text-sm font-bold text-red-700">Delete</button></form></div></div>)}</div></>;
}
