import { addBlockedDate, deleteBlockedDate, saveAvailability } from "@/actions/admin";
import { prisma } from "@/lib/prisma";
import { dateOnlyString } from "@/lib/utils";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";

const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export default async function AvailabilityPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [availability, blockedDates, query] = await Promise.all([prisma.availability.findMany({ orderBy: { dayOfWeek: "asc" } }), prisma.blockedDate.findMany({ orderBy: { date: "asc" } }), searchParams]);
  const map = new Map<number, (typeof availability)[number]>(availability.map((a) => [a.dayOfWeek, a] as const));
  return <><AdminPageHeader title="Availability" description="Define weekly consultation hours, slot duration and blocked dates." />{query.saved && <div className="alert-success mb-5">Availability updated.</div>}{query.error && <div className="alert-error mb-5">{query.error}</div>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{dayNames.map((day, dayOfWeek) => { const a = map.get(dayOfWeek); return <form action={saveAvailability} key={day} className="card p-5"><input type="hidden" name="dayOfWeek" value={dayOfWeek} /><h2 className="font-extrabold">{day}</h2><div className="mt-4 grid grid-cols-2 gap-3"><div><label className="label">Start</label><input className="field" name="startTime" type="time" defaultValue={a?.startTime || "09:00"} /></div><div><label className="label">End</label><input className="field" name="endTime" type="time" defaultValue={a?.endTime || "17:00"} /></div></div><div className="mt-3"><label className="label">Slot duration (minutes)</label><input className="field" name="slotDuration" type="number" min="15" step="15" defaultValue={a?.slotDuration || 60} /></div><label className="mt-4 flex items-center gap-2 font-semibold"><input type="checkbox" name="active" defaultChecked={a?.active ?? false} /> Available</label><button className="btn btn-primary mt-4">Save {day}</button></form>; })}</div><div className="mt-8 grid gap-6 lg:grid-cols-2"><form action={addBlockedDate} className="card p-6"><h2 className="text-xl font-extrabold">Block a date</h2><div className="mt-4"><label className="label">Date</label><input className="field" type="date" name="date" required /></div><div className="mt-4"><label className="label">Reason (optional)</label><input className="field" name="reason" /></div><button className="btn btn-primary mt-4">Block Date</button></form><div className="card p-6"><h2 className="text-xl font-extrabold">Blocked dates</h2><div className="mt-4 space-y-3">{blockedDates.map((b) => <div key={b.id} className="flex items-center justify-between gap-3 border-b border-[#e5e7eb] pb-3"><div><strong>{dateOnlyString(b.date)}</strong>{b.reason && <p className="muted text-sm">{b.reason}</p>}</div><form action={deleteBlockedDate}><input type="hidden" name="id" value={b.id} /><button className="font-bold text-red-700">Remove</button></form></div>)}{blockedDates.length === 0 && <p className="muted">No blocked dates.</p>}</div></div></div></>;
}
